### ISSUE TITLE
You're going a little too quickly. Please try again in a few seconds

### ISSUE THREAD

**Issue by mcutting** [ReFlar/gamification#53] opened 2019-05-16 09:57 UTC
Hi Everyone - seem to be getting this message despite disabling a variety of extensions, and even disabling floodgate completely (via floodgate.php - see below)

```
public function assertNotFlooding(User $actor)
{
// if ($this->isFlooding($actor)) {
// throw new FloodingException;
// }
}
```
Odd thing is that it appeared to be working for quite some time, then only recently, stopped. No matter what extensions I disable, the issue persists. Has anyone seen this before ?

Thanks

**Comment by Ralkage** [comment] 2019-05-16 17:04
It looks like you identified the actual issue and posted it on Flarum discuss. As a note before I close this issue, this issue was not caused by this extension and the resolution was posted [here](https://discuss.flarum.org/d/20014-you-re-going-a-little-too-quickly-please-try-again-in-a-few-seconds/5).

**Closed by Ralkage** 2019-05-16 17:04 UTC
